embabel:
  models:
    default-llm: gpt-oss:120b
    llms:
      cheapest: gpt-oss:120b
      normal: gpt-oss:120b
  agent:
    platform:
      ranking:
        llm: gpt-oss:120b
      models:
        openai:
          custom:
            api-key: not-set
            base-url: http://192.168.18.30:11434
            models: gpt-oss:120b
