spring:
  shell:
    interactive:
      enabled: false
    noninteractive:
      enabled: true
    context:
      close: true
embabel:
  agent:
    shell:
        interactive:
          enabled: false
