spring:
  ai:
    ollama:
      base-url: http://192.168.18.30:11434

embabel:
  models:
    default-llm: gpt-oss:120b
    default-embedding-model: qwen3-embedding:latest

    llms:
      simple: gpt-oss:120b
      normal: gpt-oss:120b
      performant: gpt-oss:120b

  agent:
    platform:
