spring:
  profiles:
    active: gemini
  main:
    banner-mode: off
    log-startup-info: false

# JWLEE CLI UI configuration
cli:
  ui:
    title: "JWLEE CLI"
    help-text: "도움말은 help / Ctrl+D 로 종료"
    greeting: "오늘도 좋은 하루 되세요."

logging:
  file:
    name: .shell.log
  level:
    root: WARN
    org.apache.lucene: WARN
      # org.springframework.shell: INFO
      # com.embabel: INFO

embabel:
  agent:
    platform:
      http-client:
        read-timeout: 180s
      llm-operations:
        prompts:
          default-timeout: 180s
        data-binding:
          max-attempts: 15
      models:
        openai:
          max-attempts: 30
          backoff-millis: 6000
          backoff-multiplier: 1.5
          backoff-max-interval: 180000
    shell:
        redirect-log-to-file: true
        web-application-type: none
        command:
          exit-enabled: true
          quit-enabled: true
        interactive:
          enabled: true
          history-enabled: true
    rag:
      lucene:
        dir: target/lucene-index
      import:
        dir: knowledge

presentation:
  output:
    dir: output/slides
  merged:
    file:
      path: /Users/jwlee/Documents/obsidian/+Encounters/presentation_test.md

app:
  obsidian:
    vault-path: obsidian-vault
    repo-url: https://github.com/woojung3/obsidian
  integration:
    google:
      client-id: ${GOOGLE_CLIENT_ID:}
      client-secret: ${GOOGLE_CLIENT_SECRET:}
      refresh-token: ${GOOGLE_REFRESH_TOKEN:}
  chatbot:
    rag-dir: "output/rag-chatbot"
  confluence:
    baseUrl: https://auto-jira.atlassian.net/wiki
    email: jwlee@autocrypt.io
    apiToken: ${CONFLUENCE_API_TOKEN:}
    space-key: "camlab"
  jira:
    baseUrl: https://auto-jira.atlassian.net
    projectKey: "VP"
  teams:
    webhookUrl: ${TEAMS_WEBHOOK_URL:}
