server:
  port: 8081

spring:
  application:
    name: jwlee-cowork-web
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

embabel:
  models:
    default-llm: gemini-2.5-flash
    default-embedding-model: gemini-embedding-001
    llms:
      simple: gemini-2.5-flash
      normal: gemini-3-flash-preview
  agent:
    platform:
      models:
        googlegenai:
          api-key: ${GEMINI_API_KEY}
